<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accommodation Count' => '',
    'Accommodation Date' => '',
    'Accommodation ID' => '',
    'ID' => '',
    'ISO-639-2' => '',
    'Name (Local)' => '',
    'Name (Native)' => '',
    'Here you can request or offer an accomodation for the event.' =>
        'Ici vous pouvez demander ou offrir un logement pour l\'événement.',
    'Request Count' => '',
    'Request ID' => '',
    'Requests' => '',
    'Response Date' => '',
    'Status' => '',
    'Supplies' => '',
    'Supply ID' => '',
    'To' => '',
    'User ID' => '',
    'Request Accomodation' => '@@@@',
    'Accept' => 'Accepter',
    'Accommodation Provided' => 'Places disponibles',
    'Account Verification' => 'Vérification du Compte',
    'Are you sure you want to delete this item?' => 'Êtes-vous sûr de vouloir supprimer cet élément?',
    'Create' => 'Créer',
    'Date' => 'Date',
    'Delete' => 'Supprimer',
    'Description' => 'Description',
    'Find Hosting' => 'Trouver',
    'From' => 'De',
    'Hosting &amp; Accommodation' => 'Hébergement',
    'Is Default' => 'Défaut',
    'Is New' => 'Nouveau',
    'Kitchen' => 'Cuisine',
    'Kitchen available' => 'Cuisine disponible',
    'Language' => 'Langue',
    'Login with Existing Account' => 'Connection avec un compte existant',
    'No Provisions Available' => 'Pas de comodité',
    'No response submitted' => 'Pas de réponse envoyée',
    'Offer Hosting' => 'Proposer',
    'Private Description' => 'Description privée',
    'Provisions' => 'Comodités',
    'Public Description' => 'Description publique',
    'Register a New Account' => 'Enregistrer un nouveau compte',
    'Remove Offer' => 'Retirer une offre',
    'Request Accommodation' => 'Envoyer une demande',
    'Request Message' => 'Message',
    'Request Response' => 'Réponse',
    'Reset' => 'Réinitialiser',
    'Respond' => 'Réponse',
    'Response Message' => 'Réponse',
    'Search' => 'Recherche',
    'Send' => 'Envoyer',
    'Shower' => 'Douche',
    'Shower available' => 'Douche disponible',
    'Update' => 'Mettre à jour',
    'Update My Offer' => 'Mettre à jour mon offre',
    'Update Offer' => 'Mettre à jour l\'offre',
    'Verification Code' => 'Code de Vérification',
    'Wifi' => 'Wifi',
    'Wifi available' => 'Wifi disponible',
];
