<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'confirmation_subject' => 'TTIP Game Over Round #2 - Registratie Voltooien',
    'confirmation_body' => 'Gebruik de link om u registratie te voltooien.',
    'reset_subject' => 'TTIP Game Over Round #2 - Wachtwoord Wijzigen',
    'reset_body' => 'Gebruik de link om uw wachtwoord te wijzigen',
    'salutation' => 'Hoi',
    'signature' => 'Tot Snel - De TTIP Game Over Team',
];
