<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accept' => 'Accepter',
    'Accommodation Count' => '',
    'Accommodation Date' => '',
    'Accommodation ID' => '',
    'Account Verification' => 'Vérification du compte',
    'Are you sure you want to delete this item?' => 'Êtes-vous sûr de vouloir supprimer cet élément?',
    'Create' => 'Créer',
    'Date' => 'Date',
    'Delete' => 'Supprimer',
    'Description' => 'Description',
    'Find Hosting' => 'Trouver un Hébergement',
    'From' => 'De',
    'ID' => '',
    'ISO-639-2' => '',
    'Is Default' => 'Défaut',
    'Is New' => 'Nouveau',
    'Kitchen' => 'Cuisine',
    'Kitchen available' => 'Cuisine disponible',
    'Language' => 'Langue',
    'Login with Existing Account' => 'Connection avec un Compte Existant',
    'Name (Local)' => '',
    'Name (Native)' => '',
    'No Provisions Available' => 'Pas de Comodité',
    'No response submitted' => 'Pas de réponse envoyée',
    'Offer Hosting' => 'Proposer un Hébergement',
    'Private Description' => 'Description Privée',
    'Public Description' => 'Description Publique',
    'Register a New Account' => 'Enregistrer un Nouveau Compte',
    'Remove Offer' => '',
    'Request Accommodation' => '',
    'Request Accomodation' => '',
    'Request Count' => '',
    'Request ID' => '',
    'Request Message' => '',
    'Request Response' => '',
    'Requests' => '',
    'Reset' => '',
    'Respond' => '',
    'Response Date' => '',
    'Response Message' => '',
    'Search' => '',
    'Send' => '',
    'Shower' => '',
    'Shower available' => '',
    'Status' => '',
    'Supplies' => '',
    'Supply ID' => '',
    'To' => '',
    'Update' => '',
    'Update My Offer' => '',
    'Update Offer' => '',
    'User ID' => '',
    'Verification Code' => '',
    'Wifi' => '',
    'Wifi available' => '',
];
