<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accept' => '',
    'Accommodation Count' => '',
    'Accommodation Date' => '',
    'Accommodation ID' => '',
    'Accommodation Provided' => '',
    'Account Verification' => '',
    'Are you sure you want to delete this item?' => '',
    'Create' => '',
    'Date' => '',
    'Delete' => '',
    'Description' => '',
    'Find Hosting' => '',
    'From' => '',
    'ID' => '',
    'ISO-639-2' => '',
    'Is Default' => '',
    'Is New' => '',
    'Kitchen' => '',
    'Kitchen available' => '',
    'Language' => '',
    'Login with Existing Account' => '',
    'Name (Local)' => '',
    'Name (Native)' => '',
    'No Provisions Available' => '',
    'No response submitted' => '',
    'Offer Hosting' => '',
    'Private Description' => '',
    'Provisions' => '',
    'Public Description' => '',
    'Register a New Account' => '',
    'Remove Offer' => '',
    'Request Accommodation' => '',
    'Request Count' => '',
    'Request ID' => '',
    'Request Message' => '',
    'Request Response' => '',
    'Requests' => '',
    'Reset' => '',
    'Respond' => '',
    'Response Date' => '',
    'Response Message' => '',
    'Search' => '',
    'Send' => '',
    'Shower' => '',
    'Shower available' => '',
    'Status' => '',
    'Supplies' => '',
    'Supply ID' => '',
    'To' => '',
    'Update' => '',
    'Update My Offer' => '',
    'Update Offer' => '',
    'User ID' => '',
    'Verification Code' => '',
    'Wifi' => '',
    'Wifi available' => '',
    'Request Accomodation' => '@@@@',
];
