<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accept' => '',
    'Accommodation Count' => '',
    'Accommodation Date' => '',
    'Accommodation ID' => '',
    'Accommodation Provided' => '',
    'Account Verification' => '',
    'Are you sure you want to delete this item?' => '',
    'Create' => '',
    'Date' => '',
    'Delete' => '',
    'Description' => '',
    'Find Hosting' => '',
    'From' => '',
    'Here you can request or offer an accomodation for the event.' => '',
    'Hosting &amp; Accommodation' => '',
    'ID' => '',
    'ISO-639-2' => '',
    'Is Default' => '',
    'Is New' => '',
    'Kitchen' => '',
    'Kitchen available' => '',
    'Language' => '',
    'Name (Local)' => '',
    'Name (Native)' => '',
    'No Provisions Available' => '',
    'No response submitted' => '',
    'Offer Hosting' => '',
    'Private Description' => '',
    'Provisions' => '',
    'Public Description' => '',
    'Remove Offer' => '',
    'Request Accommodation' => '',
    'Request Count' => '',
    'Request ID' => '',
    'Request Message' => '',
    'Request Response' => '',
    'Requests' => '',
    'Reset' => '',
    'Respond' => '',
    'Response Date' => '',
    'Response Message' => '',
    'Search' => '',
    'Send' => '',
    'Shower' => '',
    'Shower available' => '',
    'Sign Up' => '',
    'Status' => '',
    'Supplies' => '',
    'Supply ID' => '',
    'To' => '',
    'Update' => '',
    'Update My Offer' => '',
    'Update Offer' => '',
    'User ID' => '',
    'Verification Code' => '',
    'Wifi' => '',
    'Wifi available' => '',
    'Login with Existing Account' => '@@@@',
    'Register a New Account' => '@@@@',
    'account.msg.confirmation' => 'This is nearly done! Please check your mailbox to confirm your registration.',
    'host.date.title' => 'Input the number of available accodommations for each day.',
    'host.description_private.placeholder' => 'Write a message that will automatically be sent by mail to the persons that request accomodations.',
    'host.description_public.placeholder' => 'Describe your place and yourself. This will be available to the public.',
];
