<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'confirmation_subject' => 'Account Confirmation',
    'confirmation_body' => 'Follow the link below to complete account registration',
    'request_in_subject' => 'You have received an incoming request. You can respond to it, by following the link below',
    'request_in_body' => 'You have received an incoming request. You can respond to it, by following the link below',
    'reset_subject' => 'Password Reset',
    'reset_body' => 'Follow the link below to reset your account password',
    'salutation' => 'Hi there',
    'signature' => 'See you soon - The TTIP Game Over Team',
    'request_in_subject{username}' => '{username} has send you an incoming request.',
    'request_in_body' => 'You have received an incoming request. You can respond to it, by following the link below',
    'request_out_subject{username}{status}' => '{username} has {status} to your request.',
    'request_out_body' => 'You have received a reply to your request.',
];
